-- MySQL Script generated by MySQL Workbench
-- Wed Jan 10 10:10:07 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema team_topic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema team_topic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `team_topic` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema team_topic
-- -----------------------------------------------------
USE `team_topic` ;


-- -----------------------------------------------------
-- Table `team_topic`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team_topic`.`user` ;

CREATE TABLE IF NOT EXISTS `team_topic`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `role` TINYINT(2) ZEROFILL NOT NULL,
  `updatetime` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `createtime` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team_topic`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team_topic`.`team` ;

CREATE TABLE IF NOT EXISTS `team_topic`.`team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `updatetime` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `createtime` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team_topic`.`user_has_team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team_topic`.`user_has_team` ;

CREATE TABLE IF NOT EXISTS `team_topic`.`user_has_team` (
  `user_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `team_id`),
  INDEX `fk_user_has_team_team1_idx` (`team_id` ASC),
  INDEX `fk_user_has_team_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_team_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `team_topic`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_team_team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `team_topic`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team_topic`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team_topic`.`post` ;

CREATE TABLE IF NOT EXISTS `team_topic`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `team_id` INT NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(300) NULL,
  `zindex` INT NOT NULL,
  `positionx` INT NOT NULL,
  `positiony` INT NOT NULL,
  `height` INT NOT NULL,
  `width` INT NOT NULL,
  `status` TINYINT(2) NOT NULL,
  `color` VARCHAR(20) NULL,
  `updatetime` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `createtime` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_post_team1_idx` (`team_id` ASC),
  CONSTRAINT `fk_post_team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `team_topic`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

